module.exports = {
    JWT_TOKEN_HASH_ALGO: 'HS256',
    JWT_TOKEN_EXPIRATION: 18000000,
    JWT_SECRET_OR_KEY: 'vdkhoa7498',
    JWT_TOKEN_PREFIX: 'JWT',
    ACTIVATE_EMAIL_JWT_SECRET: 'vdkhoa7498',
    ACTIVATE_EMAIL_TOKEN_EXPIRED_TIME: '24h',
    SENDGRID_API_KEY : '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',
    TEAM_EMAIL : 'vdkhoa7498@gmail.com'
  }
  